name= input("Digite o nome do filme:\n ")
year= int(input("Digite o ano de lançamento do filme:\n ")) 
note= float(input("Digite a nota do filme:\n "))
print("O filme {} \nfoi lançado em {}".format(name, year))
print("A nota do filme é {}".format(note))